grasp_mapper:
  # 这个参数用于缩放夹爪到最后的tensor上
  max_width_px_in_tensor: 10
  min_width_px_in_tensor: 10
  final_width: 32
  final_height: 32

policy:
  num_seed_samples: 200
  num_gmm_samples: 50
  num_iters: 3
  gmm_refit_p: 0.25
  gmm_component_frac: 0.4
  gmm_reg_covar: 0.01
  
sampler:
  max_grasp_width_px: 30
  friction_coef: 0.8
  depth_grad_thresh: 0.05
  min_grasp_dist: 0.025
  angle_dist_weight: 0.025
  min_depth_offset: 0.015
  max_depth_offset: 0.015
  depth_sample_win_height: 1
  depth_sample_win_width: 1
  depth_samples_per_grasp: 1
  
training:
  data_path: path/to/tfrecords_data
  model_file: path/to/model
  out_path: path/to/out
  summary_dir: path/to/summary
  restore: 1
  summary_step: 100
  im_height: 32
  im_width: 32
  im_channels: 1
  pose_len: 1

  dataset_buffer_size: 10000
  train_batch_size: 64
  val_batch_size: 64

  base_lr: 0.015
  decay_step_multiplier: .2   # number of times to go through training datapoints before stepping down decay rate
  decay_rate: 0.95
  metric_thresh: 0.002
  train_drop_out: 0
  train_l2_regularizer: 0.0005
  optimizer: momentum
  momentum_rate: 0.9

  fine_tune: 0
  update_fc_only: 1
  update_conv0_only: 0
  reinit_fc3: 0
  reinit_fc4: 0
  reinit_fc5: 0

data_process:
  training_percent: 0.8
  validation_percent: 0.2

  raw_path: path/to/npz_data
  out_path: path/to/tfrecords_data

  datapoint_pre_file: 5000
  # gamma分布的参数
  multiplicative_denoising: 1
  gamma_shape: 1000.00

  symmetrize: 1

  morphological: 0
  morph_open_rate: 0.25
  morph_poisson_mean: 1.5

  image_dropout: 0
  image_dropout_rate: 0.25
  dropout_poisson_mean: 1.0
  dropout_radius_shape: 3.0
  dropout_radius_scale: 1.0

  gradient_dropout: 0
  gradient_dropout_rate: 0.1
  gradient_dropout_sigma: 0.5
  gradient_dropout_shape: 15
  gradient_dropout_scale: 0.001

  gaussian_process_denoising: 1
  gaussian_process_rate: 0.5
  gaussian_process_scaling_factor: 4.0
  gaussian_process_sigma: 0.005

  border_distortion: 0
  border_grad_sigma: 1.0
  border_grad_thresh: 0.075
  border_poisson_mean: 5.0
  border_radius_shape: 5
  border_radius_scale: 0.4

  background_denoising: 0
  background_rate: 0.25
  background_min_depth: 0.0
  background_max_depth: 0.65




### GQCNN CONFIG ###
gqcnn_config:
  # basic data metrics
  im_height: 32
  im_width: 32
  im_channels: 1

  use_raw: 1

  model_path: C:/Users/13111/Documents/Robot/test/gqcnn-test/GQ-Image-Wise
  # needs to match input data mode that was used for training, determines the pose dimensions for the network
  pose_dim: 1

  # prediction batch size, in training this will be overriden by the val_batch_size in the DeepOptimizer's config file
  batch_size: 16

  # architecture
  architecture:
    conv1_1:
      filt_dim: 7
      num_filt: 64
      pool_size: 1
      pool_stride: 1  
      norm: 0
      norm_type: local_response
    conv1_2:
      filt_dim: 5
      num_filt: 64
      pool_size: 2
      pool_stride: 2
      norm: 1
      norm_type: local_response
    conv2_1:
      filt_dim: 3
      num_filt: 64
      pool_size: 1
      pool_stride: 1  
      norm: 0
      norm_type: local_response
    conv2_2:
      filt_dim: 3
      num_filt: 64
      pool_size: 1
      pool_stride: 1
      norm: 1
      norm_type: local_response
    pc1:
      out_size: 16
    # pc2:
    #   out_size: 0
    fc3:
      out_size: 1024
      drop_out: 0
      drop_rate: 0
    fc4:
      out_size: 1024  
      drop_out: 0
      drop_rate: 0 
    fc5:
      out_size: 2

  # architecture normalization constants
  radius: 2
  alpha: 2.0e-05
  beta: 0.75
  bias: 1.0
